[package]
name = "spiderman"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.13.2"
html2text = "0.12"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tempfile = "3.8"
